name: On PR

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  automerge:
    # if a PR is from this repository (not a fork), enable automerge
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.DOPPEL_BOT_ID }}
          private_key: ${{ secrets.DOPPEL_BOT_KEY }}
          
      # we enable automerge with an app token, so that workflows will trigger off of the merge
      - name: Enable automerge
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr merge --auto --squash "$PR_URL"
        shell: bash

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        allowed_prefixes: 'feat:,fix:,build:,chore:,docs:,style:,refactor:,test:,revert:'
        prefix_case_sensitive: true
        min_length: 10
        max_length: 50
